# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение с формы',
                'verbose_name_plural': 'Сообщения с формы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_tg', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_2', models.CharField(blank=True, max_length=255, verbose_name='Адрес-2')),
                ('address_2_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес-2')),
                ('address_2_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес-2')),
                ('address_2_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес-2')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Рабочие часы')),
                ('working_hours_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие часы')),
                ('working_hours_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие часы')),
                ('working_hours_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие часы')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=64, verbose_name='Телефон (доп.)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Email (доп.)')),
                ('map_iframe_src', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контакты — страница',
                'verbose_name_plural': 'Контакты — страница',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=160, verbose_name='Ученик')),
                ('parent_name', models.CharField(max_length=160, verbose_name='Родитель/опекун')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Класс (1–11)')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка на поступление',
                'verbose_name_plural': 'Заявки на поступление',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('grade__gte', 1), ('grade__lte', 11)), name='admission_grade_1_11')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admissions/documents/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contacts.admissionapplication', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявок',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
