# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_tg', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Обложка')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Видео')),
                ('category', models.CharField(choices=[('events', 'Events'), ('sport', 'Sports'), ('academic', 'Academic')], default='events', max_length=50, verbose_name='Категория')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('caption_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.newspost', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Галерея новости',
                'verbose_name_plural': 'Галереи новостей',
                'ordering': ['-created_at'],
            },
        ),
    ]
