# Generated by Django 5.2.10 on 2026-02-12 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusMapZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('under-construction', 'Under Construction'), ('not-school-territory', 'Not School Territory'), ('entrance', 'Entrance'), ('main-building', 'Main Building'), ('yard', 'Yard'), ('trees-garden', 'Trees Garden'), ('football-stadium', 'Football Stadium')], help_text='Одна запись на каждую зону карты.', max_length=64, unique=True, verbose_name='Ключ зоны')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_map/zones/', verbose_name='Изображение')),
                ('x_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='X (%)')),
                ('y_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Y (%)')),
                ('width_pct', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Ширина (%)')),
                ('height_pct', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Высота (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('show_in_buttons', models.BooleanField(default=True, verbose_name='Показывать в кнопках')),
                ('is_clickable', models.BooleanField(default=True, verbose_name='Кликабельно')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Зона карты кампуса',
                'verbose_name_plural': 'Зоны карты кампуса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampusMapZonePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название части')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название части')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название части')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название части')),
                ('description', models.TextField(blank=True, verbose_name='Описание части')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание части')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание части')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание части')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_map/parts/', verbose_name='Изображение части')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='site_content.campusmapzone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Часть зоны кампуса',
                'verbose_name_plural': 'Части зон кампуса',
                'ordering': ['order', 'id'],
            },
        ),
    ]
