# Generated by Django 5.2.10 on 2026-02-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_backfill_campus_part_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='category',
        ),
        migrations.AddField(
            model_name='infrastructureitem',
            name='zone',
            field=models.CharField(choices=[('under-construction', 'Under Construction'), ('not-school-territory', 'Not School Territory'), ('entrance', 'Entrance'), ('main-building', 'Main Building'), ('yard', 'Yard'), ('trees-garden', 'Trees Garden'), ('football-stadium', 'Football Stadium')], default='main-building', max_length=64, verbose_name='Зона'),
        ),
    ]
