# Generated by Django 5.2.10 on 2026-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_remove_infrastructureitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusmapzone',
            name='zone',
            field=models.CharField(choices=[('under-construction', 'Under Construction'), ('future-buildings', 'Future Buildings'), ('not-school-territory', 'Not School Territory'), ('entrance', 'Entrance'), ('main-building', 'Main Building'), ('yard', 'Yard'), ('trees-garden', 'Trees Garden'), ('football-stadium', 'Football Stadium')], help_text='Одна запись на каждую зону карты.', max_length=64, unique=True, verbose_name='Ключ зоны'),
        ),
        migrations.AlterField(
            model_name='infrastructureitem',
            name='zone',
            field=models.CharField(choices=[('under-construction', 'Under Construction'), ('future-buildings', 'Future Buildings'), ('not-school-territory', 'Not School Territory'), ('entrance', 'Entrance'), ('main-building', 'Main Building'), ('yard', 'Yard'), ('trees-garden', 'Trees Garden'), ('football-stadium', 'Football Stadium')], default='main-building', max_length=64, verbose_name='Зона'),
        ),
    ]
