# Generated by Django 5.2.10 on 2026-02-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_align_campus_map_frames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfrastructureItem',
        ),
    ]
