# Generated by Django 5.2.10 on 2026-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0014_methodical_materials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['album__order', 'order', '-created_at', '-id'], 'verbose_name': 'Фото (галерея)', 'verbose_name_plural': 'Фото (галерея)'},
        ),
        migrations.AddField(
            model_name='methodicalmaterial',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='methodicalmaterial',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='methodicalmaterial',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='campusmapzone',
            name='zone',
            field=models.CharField(choices=[('under-construction', 'Under Construction'), ('future-buildings', 'Future Buildings'), ('future-gym', 'Future Building (Gym)'), ('not-school-territory', 'Not School Territory'), ('entrance', 'Entrance'), ('main-building', 'Main Building'), ('yard', 'Yard'), ('trees-garden', 'Trees Garden'), ('football-stadium', 'Football Stadium')], help_text='Одна запись на каждую зону карты.', max_length=64, unique=True, verbose_name='Ключ зоны'),
        ),
    ]
