# Generated by Django 5.2.10 on 2026-02-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0015_alter_galleryimage_options_and_more'),
        ('site_content', '0016_education_type'),
    ]

    operations = [
    ]
