# Generated by Django 5.2.10 on 2026-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0017_merge_20260227_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtype',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='text_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='studentscommunitymember',
            name='role_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='studentscommunitymember',
            name='role_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='studentscommunitymember',
            name='role_title_tg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='members_intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Участники (введение)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='members_intro_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Участники (введение)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='members_intro_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Участники (введение)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 2)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 2)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_2_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 2)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 1)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 1)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_text_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст: Миссия (абзац 1)'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок: Миссия'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок: Миссия'),
        ),
        migrations.AddField(
            model_name='studentscommunitypage',
            name='mission_title_tg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок: Миссия'),
        ),
    ]
