# Generated by Django 5.2.10 on 2026-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_extracurricular', '0002_update_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='place_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='place_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='place_tg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extracurricularschedule',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
