# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Категория')),
                ('name_tg', models.CharField(max_length=120, null=True, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='Категория')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория школьных мероприятий',
                'verbose_name_plural': 'Категории школьных мероприятий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('place_tg', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('place_ru', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('place_en', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_events/', verbose_name='Изображение (обложка)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.schoolclass', verbose_name='Класс')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events_school.schooleventcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Школьное мероприятие (по классу)',
                'verbose_name_plural': 'Школьные мероприятия (по классам)',
                'ordering': ['-start_at', 'school_class__grade', 'school_class__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_events/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('caption_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events_school.schoolevent', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Галерея школьного мероприятия',
                'verbose_name_plural': 'Галереи школьных мероприятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEventItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Пункт')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Пункт')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Пункт')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Пункт')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('details_tg', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('details_ru', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('details_en', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('time_hint', models.CharField(blank=True, max_length=64, verbose_name='Время (текст)')),
                ('time_hint_tg', models.CharField(blank=True, max_length=64, null=True, verbose_name='Время (текст)')),
                ('time_hint_ru', models.CharField(blank=True, max_length=64, null=True, verbose_name='Время (текст)')),
                ('time_hint_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Время (текст)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='events_school.schoolevent', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'План школьного мероприятия',
                'verbose_name_plural': 'Планы школьных мероприятий',
                'ordering': ['event_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Слаг')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('body_tg', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='school_events/posts/covers/', verbose_name='Обложка')),
                ('video', models.FileField(blank=True, null=True, upload_to='school_events/posts/videos/', verbose_name='Видео')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events_school.schoolevent', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Пост школьного мероприятия',
                'verbose_name_plural': 'Посты школьных мероприятий',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEventPostGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_events/posts/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('caption_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events_school.schooleventpost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Галерея поста школьного мероприятия',
                'verbose_name_plural': 'Галереи постов школьных мероприятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolevent',
            constraint=models.UniqueConstraint(fields=('school_class', 'start_at', 'title'), name='uniq_school_class_start_title'),
        ),
        migrations.AddConstraint(
            model_name='schoolevent',
            constraint=models.UniqueConstraint(fields=('school_class', 'start_at', 'title_tg'), name='uniq_school_class_start_title-title_tg'),
        ),
        migrations.AddConstraint(
            model_name='schoolevent',
            constraint=models.UniqueConstraint(fields=('school_class', 'start_at', 'title_ru'), name='uniq_school_class_start_title-title_ru'),
        ),
        migrations.AddConstraint(
            model_name='schoolevent',
            constraint=models.UniqueConstraint(fields=('school_class', 'start_at', 'title_en'), name='uniq_school_class_start_title-title_en'),
        ),
        migrations.AddConstraint(
            model_name='schooleventpost',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='uniq_school_event_post_slug'),
        ),
    ]
