# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('name_tg', models.CharField(max_length=160, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=160, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Изображение')),
                ('schedule_text', models.TextField(blank=True, verbose_name='Расписание (текст)')),
                ('schedule_text_tg', models.TextField(blank=True, null=True, verbose_name='Расписание (текст)')),
                ('schedule_text_ru', models.TextField(blank=True, null=True, verbose_name='Расписание (текст)')),
                ('schedule_text_en', models.TextField(blank=True, null=True, verbose_name='Расписание (текст)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('leader', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Кружок/секция',
                'verbose_name_plural': 'Кружки/секции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clubs/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('caption_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clubs.club', verbose_name='Кружок/секция')),
            ],
            options={
                'verbose_name': 'Галерея кружка/секции',
                'verbose_name_plural': 'Галереи кружков/секций',
                'ordering': ['-created_at'],
            },
        ),
    ]
