# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Предмет')),
                ('name_tg', models.CharField(max_length=255, null=True, verbose_name='Предмет')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Предмет')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=160, verbose_name='Город')),
                ('city_tg', models.CharField(max_length=160, null=True, verbose_name='Город')),
                ('city_ru', models.CharField(max_length=160, null=True, verbose_name='Город')),
                ('city_en', models.CharField(max_length=160, null=True, verbose_name='Город')),
                ('country', models.CharField(max_length=160, verbose_name='Страна')),
                ('country_tg', models.CharField(max_length=160, null=True, verbose_name='Страна')),
                ('country_ru', models.CharField(max_length=160, null=True, verbose_name='Страна')),
                ('country_en', models.CharField(max_length=160, null=True, verbose_name='Страна')),
                ('latitude', models.FloatField(verbose_name='Широта (lat)')),
                ('longitude', models.FloatField(verbose_name='Долгота (lng)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок карточки')),
                ('title_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок карточки')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок карточки')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок карточки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='graduates/destinations/', verbose_name='Фото/превью')),
                ('assistant_url', models.URLField(blank=True, verbose_name='Ссылка (кнопка)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Локация выпускников (международная)',
                'verbose_name_plural': 'Локации выпускников (международные)',
                'ordering': ['country', 'city', 'id'],
                'indexes': [models.Index(fields=['is_public', 'country', 'city'], name='people_grad_is_publ_a32192_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='graduate_destination_lat_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='graduate_destination_lng_range')],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Класс')),
                ('grade', models.PositiveSmallIntegerField(default=1, verbose_name='Ступень (1–11)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['grade', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('grade__gte', 1), ('grade__lte', 11)), name='class_grade_1_11')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('full_name_tg', models.CharField(max_length=255, null=True, verbose_name='Полное имя')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='Полное имя')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='Полное имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.schoolclass', verbose_name='Класс')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (логин)')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['school_class__grade', 'school_class__name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число — тем выше в списке', verbose_name='Порядок')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('full_name_tg', models.CharField(max_length=160, null=True, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=160, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=160, null=True, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('admin', 'Administration'), ('teacher', 'Teachers'), ('staff', 'Staff')], max_length=16, verbose_name='Категория')),
                ('position', models.CharField(blank=True, max_length=160, verbose_name='Должность')),
                ('position_tg', models.CharField(blank=True, max_length=160, null=True, verbose_name='Должность')),
                ('position_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('bio_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (логин)')),
                ('subjects', models.ManyToManyField(blank=True, to='people.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateStudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО выпускника')),
                ('full_name_tg', models.CharField(max_length=255, null=True, verbose_name='ФИО выпускника')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО выпускника')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО выпускника')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='graduates/records/', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='graduates/records/', verbose_name='Фото 2')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('university_name', models.CharField(max_length=255, verbose_name='Университет')),
                ('university_name_tg', models.CharField(max_length=255, null=True, verbose_name='Университет')),
                ('university_name_ru', models.CharField(max_length=255, null=True, verbose_name='Университет')),
                ('university_name_en', models.CharField(max_length=255, null=True, verbose_name='Университет')),
                ('program', models.CharField(blank=True, max_length=255, verbose_name='Программа/специализация')),
                ('program_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Программа/специализация')),
                ('program_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Программа/специализация')),
                ('program_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Программа/специализация')),
                ('degree', models.CharField(blank=True, max_length=64, verbose_name='Степень')),
                ('degree_tg', models.CharField(blank=True, max_length=64, null=True, verbose_name='Степень')),
                ('degree_ru', models.CharField(blank=True, max_length=64, null=True, verbose_name='Степень')),
                ('degree_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Степень')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год поступления')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='people.graduatedestination', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Выпускник за рубежом',
                'verbose_name_plural': 'Выпускники за рубежом',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['destination', 'is_public', 'order', 'id'], name='people_grad_destina_fc9bff_idx')],
            },
        ),
    ]
