# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Тип соревнования')),
                ('name_tg', models.CharField(max_length=120, null=True, unique=True, verbose_name='Тип соревнования')),
                ('name_ru', models.CharField(max_length=120, null=True, unique=True, verbose_name='Тип соревнования')),
                ('name_en', models.CharField(max_length=120, null=True, unique=True, verbose_name='Тип соревнования')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип соревнования',
                'verbose_name_plural': 'Типы соревнований',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Год')),
                ('icon', models.CharField(default='workspace_premium', max_length=64, verbose_name='Иконка (Material Symbol)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_honors/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Награда школы',
                'verbose_name_plural': 'Награды школы',
                'ordering': ['order', '-year', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соревнования')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название соревнования')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название соревнования')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название соревнования')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Год')),
                ('level', models.CharField(choices=[('school', 'School'), ('city', 'City'), ('region', 'Regional'), ('republic', 'Republic'), ('international', 'International')], default='school', max_length=32, verbose_name='Уровень')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Где проходил (место)')),
                ('location_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Где проходил (место)')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Где проходил (место)')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Где проходил (место)')),
                ('result_place', models.CharField(blank=True, max_length=64, verbose_name='Результат/место')),
                ('result_place_tg', models.CharField(blank=True, max_length=64, null=True, verbose_name='Результат/место')),
                ('result_place_ru', models.CharField(blank=True, max_length=64, null=True, verbose_name='Результат/место')),
                ('result_place_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Результат/место')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.subject', verbose_name='Предмет/дисциплина')),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.competitiontype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Результат соревнования',
                'verbose_name_plural': 'Результаты соревнований',
                'ordering': ['-year', 'level', 'competition_type__order', 'title'],
            },
        ),
    ]
