# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('menu_type', models.CharField(choices=[('public', 'Public'), ('student', 'Student'), ('teacher', 'Teacher')], default='public', max_length=16, verbose_name='Тип меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Показывать в футере')),
                ('route_name', models.CharField(blank=True, max_length=255, verbose_name='Имя маршрута')),
                ('url_kwargs_json', models.TextField(blank=True, verbose_name='Параметры URL (JSON)')),
                ('custom_url', models.CharField(blank=True, max_length=255, verbose_name='Пользовательский URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'id'],
            },
        ),
    ]
