# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/files/', verbose_name='Файл')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Материал задания',
                'verbose_name_plural': 'Материалы заданий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Название задания')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название задания')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('assigned_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='Сдать до')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дополнительное задание',
                'verbose_name_plural': 'Дополнительные задания',
                'ordering': ['-assigned_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='День недели')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать гостям')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Расписание урока',
                'verbose_name_plural': 'Расписание уроков',
                'ordering': ['school_class__grade', 'school_class__name', 'weekday', 'slot__number'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('title_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/files/', verbose_name='Файл')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Материал урока',
                'verbose_name_plural': 'Материалы уроков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема/название')),
                ('title_tg', models.CharField(max_length=255, null=True, verbose_name='Тема/название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Тема/название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Тема/название')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'План урока',
                'verbose_name_plural': 'Планы уроков',
                'ordering': ['-date', '-created_at', 'school_class__grade', 'school_class__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Кабинет/аудитория')),
                ('name_tg', models.CharField(max_length=64, null=True, verbose_name='Кабинет/аудитория')),
                ('name_ru', models.CharField(max_length=64, null=True, verbose_name='Кабинет/аудитория')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='Кабинет/аудитория')),
                ('floor', models.CharField(blank=True, max_length=16, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='№ урока')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Слот времени',
                'verbose_name_plural': 'Слоты времени',
                'ordering': ['number'],
            },
        ),
    ]
