# Generated by Django 5.2.10 on 2026-01-31 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.schoolclass', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='assignmentmaterial',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.classassignment', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='classlesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.schoolclass', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='classlesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='classlesson',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.schoolclass', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff', verbose_name='Ответственный учитель'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.lessonplan', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='classlesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.room', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='classlesson',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.timeslot', verbose_name='Время (урок)'),
        ),
        migrations.AddConstraint(
            model_name='classlesson',
            constraint=models.UniqueConstraint(fields=('school_class', 'weekday', 'slot'), name='uniq_class_weekday_slot'),
        ),
    ]
