# Generated by Django 5.2.10 on 2026-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_update_plans_assignments_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['-date', '-created_at', 'grade', 'subject__name'], 'verbose_name': 'План урока', 'verbose_name_plural': 'Планы уроков'},
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс (1–11)'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс (1–11)'),
        ),
    ]
